### ISSUE TITLE
[2/16미팅] 가입시 인풋필드 글자수 및 영문, 숫자 제한적용

### ISSUE THREAD

**Issue by brojkim** [repunch-io/repunch-web#41]
1. comapny name 50자 
2. comapny URL 영문,숫자 50자 
3. Phonenumber 국가번호에 "번호+(지역명)추가

**Comment by joseph-wee** [comment]
이름의 경우 2세의 경우 로마자로 II이지만 혹시 모르니 숫자 허용해놓기로 결정.
