### ISSUE TITLE
[2/16 미팅] 가입시 패스워드 정책 8자이상 / 영소+대문+숫자 

### ISSUE THREAD

**Issue by brojkim** [repunch-io/repunch-web#42]
1. 8자이상 / 영소+대문+숫자 @koolguyjeff @hyesang F/U
2. 에러케이스 안내문구 추가 @brojkim 
<img width="282" alt="스크린샷 2024-02-18 오후 3 07 49" src="https://github.com/repunch-io/repunch-web/assets/88357683/5a2b3703-c1c1-4a83-821b-f9fefbced144">

<img width="451" alt="스크린샷 2024-02-18 오후 3 08 07" src="https://github.com/repunch-io/repunch-web/assets/88357683/1e16a4fd-82c4-4b6f-8036-7251260f11fc">

https://www.figma.com/file/iX8RkkSZGfOCohlRYFtwiZ/repunch_lime?type=design&node-id=1246%3A20167&mode=design&t=PsPMazsq7j23Ne73-1

**Comment by joseph-wee** [comment]
이메일 보내면 구글메일에서 이미지 깨지는데 이는 새로운 이슈로 등록
